[plugins]
# specify a custom repo url
# note this will only be used if the plugin does not already exist
mockolo = "https://github.com/MontakOleg/asdf-mockolo"

[tools]
tuist = "4.9.0" # https://github.com/tuist/tuist/releases
mockolo = "2.0.1" # https://github.com/uber/mockolo/releases
swiftlint = "0.54.0" # https://github.com/realm/SwiftLint/releases